{% set name = "finvader" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/finvader-{{ version }}.tar.gz
  sha256: 4d1037dd4efbd4f7af47bcc1eb8d7f76d0a19c14d2991a4b067996ebfc146cbc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - pip
  run:
    - python >=3.8,<3.12
    - nltk ==3.6.2

test:
  imports:
    - finvader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PetrKorab/FinVADER
  summary: VADER sentiment classifier updated with financial lexicons
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
